string direction
string mac
string characteristic
string topic_name
string message_type
string[] member_paths
float32 rate_hz
bool enable
---
bool success
string message
string resolved_uuid
string resolved_path
string resolved_topic
string resolved_message_type
string[] resolved_member_paths
float32 resolved_rate_hz
